name = "KerrQuasinormalModes"
uuid = "a0c1a39c-d08a-4968-9445-310f7f487a47"
authors = ["Acme Corp"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
